# Generated by Django 3.1.4 on 2021-05-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_subextra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubExtra',
        ),
    ]
