# Generated by Django 3.1.4 on 2021-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_subextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
