# Generated by Django 3.1.4 on 2021-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210523_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
